version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo "build"
      - run:
           name: "export env"
           command: |
             APPNAME=`echo ${CIRCLE_BRANCH}| sed 's$/$-$'`
             APPDIR=`echo ${CIRCLE_BRANCH} | sed 's$en/$$g' | sed 's$/$-$'`
             cat <<-EOF >> $BASH_ENV
              export TERM=xterm
              export AWS_DEFAULT_REGION=us-east-1
             EOF
      - run: echo $AWS_DEFAULT_REGION

