version: 2
jobs:
  notification:
    docker:
    - image: 899938227199.dkr.ecr.ap-northeast-1.amazonaws.com/test-repo:latest
      aws_auth:
        aws_access_key_id: $AWS_ACCESS_KEY_ID
        aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
    - checkout
    - run:
        command: |
          echo "Hello from ECR"
workflows:
  version: 2
  test:
    jobs:
    - notification
