version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: echo "build"
      - run:
           name: "export env"
           command: |
             APPNAME=`echo ${CIRCLE_BRANCH}| sed 's$/$-$'`
             APPDIR=`echo ${CIRCLE_BRANCH} | sed 's$en/$$g' | sed 's$/$-$'`
             cat <<-EOF >> $BASH_ENV
              export TERM=TEST1
              export AAA=${CIRCLE_BRANCH}
              export AWS_DEFAULT_REGION=TEST2
             EOF
      - run: echo $AWS_DEFAULT_REGION
      - run: echo $TERM
      - run: echo $AAA

